local_backend: false
backend:
  name: github
  repo: nicolasvenegas/la-fauna # Tu usuario y el nombre del repo
  branch: main

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Entradas de La Fauna"
    folder: "content/posts"
    create: true
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Cuerpo", name: "body", widget: "markdown" }
